spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demohouseproject
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
      init:
        mode: never
server:
    port: 8080

security:
  jwt:
      secret-key: jwt-tokens-that-should-be-changed-production

